### ISSUE TITLE
vscode terminal metrics

### ISSUE THREAD

**Issue by chewrocca** [guicaulada/vscode-exporter#3]
**Is your feature request related to a problem? Please describe.**

no

**Describe the solution you'd like**

Looking for more clarity on these metrics that are related to the terminal:

```sh
vscode_terminals_seconds_total{name, exit_code} counter
vscode_terminals_seconds_active{name, exit_code} counter
vscode_terminals_active {name} gauge
```

Do you think we can visualize the amount of time spent within the terminal in the dashboard?  Are there any other metrics we can get from the terminal?

**Comment by guicaulada** [comment]
The `vscode_terminals_seconds_total` is calculated based on the events for openening an closing a terminal, it just calculates the time between those events. It knows which terminal got opened and closed by it's process ID.

The `vscode_terminals_seconds_active` is calculated based on the event for changing the active terminal window, if there's an active terminal when the switch happens, it stops the timer for the old one and increases it on the metric, and starts a new one for the new active terminal.

The `vscode_terminals_active` is also calculated on the open and close events, it increases when a terminal is opened and decreases when one is closed.

I have explored the main events for the terminal `onDidChangeActiveTerminal`, `onDidOpenTerminal` and `onDidCloseTerminal`. However one event I haven't explored much is `onDidChangeTerminalState`, but I don't see much we can extract from it, since the TerminalState only gives us one boolean property for `isInteractedWith`.

You should definitely be able to tell the amount of time spent within the terminal using the `vscode_terminals_seconds_active` metric.
